FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .

COPY is4.raspi.pem /usr/local/share/ca-certificates/is4.crt
RUN update-ca-certificates

ENTRYPOINT ["dotnet", "mesi-notify.dll"]
